export enum ELanguageActionType {
  ALL_LANGUAGES = 'ALL-LANGUAGES',

  SET_LANGUAGE_FILTER_FROM = 'SET-LANGUAGE-FILTER-FROM',
  SET_LANGUAGE_FILTER_TO = 'SET-LANGUAGE-FILTER-TO',

  SET_TEXT_AREA_FROM = 'SET-TEXT-AREA-FROM',
  SET_TEXT_AREA_TO = 'SET-TEXT-AREA-TO',

  SWAP_LANGUAGE = 'SWAP-LANGUAGE',
}
